on:
#  push:
#    tags:
#      - 'v*'
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # steps for building assets
      - run: |
          echo "REPLACE ME!" > assets.gz
          echo "REPLACE ME!" > hoge.zip

      - name: version
        shell: bash
        run: echo "::set-output name=version::$(cat VERSION)"
        id: version

      - name: Create Release
        id: create_release
        uses: shogo82148/actions-create-release@v1
        with:
          tag_name: v${{ steps.version.outputs.version }}
          release_name: Release v${{ steps.version.outputs.version }}

      - uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: *.{gz,zip}
          overwrite: true
