on:
#  push:
#    tags:
#      - 'v*'
  workflow_dispatch

jobs:
  create:
    runs-on: ubuntu-latest
    outputs:
      url: ${{ steps.create_release.outputs.upload_url }}    
    steps:
      - uses: actions/checkout@v2
      - name: version
        shell: bash --login {0}
        run: echo "::set-output name=version::$(cat VERSION)"
        id: version

      - name: Create Release
        id: create_release
        uses: shogo82148/actions-create-release@v1
        with:
          tag_name: v${{ steps.version.outputs.version }}
          release_name: Release v${{ steps.version.outputs.version }}
          body: auto build.
          draft: false
          prerelease: false
      
  build:
    needs: [ create ]
    runs-on: ${{ matrix.platform }}
    continue-on-error: true
    strategy:
      max-parallel: 15
      matrix:
        platform: [
            ubuntu-latest,
            windows-latest,
            macos-latest
        ]

    steps:
      - uses: actions/checkout@v2

      # steps for building assets
      - run: |
          echo "REPLACE ME!" > assets.gz
          echo "REPLACE ME!" > hoge.zip

      - name: fname_win
        shell: bash
        if: ${{ matrix.platform == 'windows-latest' }}
        run: for z in `ls *.zip`; do mv $z ${z//.zip/_win64.zip}; done

      - name: fname_linux
        if: ${{ matrix.platform == 'ubuntu-latest' }}
        run: |
          for z in `ls *.tar.gz`; do mv $z ${z//.tar.gz/_linux_x86_64.tar.gz}; done
          for z in `ls *.gz`; do mv $z ${z//.gz/_linux_x86_64.gz}; done

      - name: fname_osx
        if: ${{ matrix.platform == 'macos-latest' }}
        run: |
          for z in `ls *.tar.gz`; do mv $z ${z//.tar.gz/-macosx_10_16_x86_64.tar.gz}; done
          for z in `ls *.gz`; do mv $z ${z//.gz/-macosx_10_16_x86_64.gz}; done

      - uses: shogo82148/actions-upload-release-asset@v1
        if: ${{ matrix.platform != 'windows-latest' }}
        with:
          upload_url: ${{ needs.create.outputs.url }}
          asset_path: "*.gz"
          overwrite: true

      - uses: shogo82148/actions-upload-release-asset@v1
        if: ${{ matrix.platform == 'windows-latest' }}
        with:
          upload_url: ${{ needs.create.outputs.url }}
          asset_path: "*.zip"
          overwrite: true
